### ISSUE TITLE
    image: <img src={`${base64Image}`} /> broken

### ISSUE THREAD

**Issue by ericjuta** [wevm/frog-archived#118]
### Describe the bug

broke recently, only matches on src starting with /

### Frog Version

0.5.5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by jxom** [comment]
What's broken? Can you provide a minimal reproduction? Works for me.

**Comment by ericjuta** [comment]
image doesn't render a raw base64 string anymore using node canvas, png or jpeg

used to work in version 0.4.6

**Comment by ericjuta** [comment]
where base64Image = canvas.createCanvas(w,h).toDataURL('image/png');

**Comment by jxom** [comment]
Thanks. Will take a look

**Comment by dalechyn** [comment]
Tested and cannot face any issues. You can try it out here https://github.com/dalechyn/frog/tree/canvas-investigation.
![Screenshot 2024-03-12 at 14 57 32](https://github.com/wevm/frog/assets/35642018/0cbf8ee5-56da-489e-b315-f6bdaa90d4fe)
```ts
app.frame('/base-64/canvas', (c) => {
  const { status } = c
  const canvas = createCanvas(200, 200)
  const ctx = canvas.getContext('2d')
  // Write "Awesome!"
  ctx.font = '30px Impact'
  ctx.rotate(0.1)
  ctx.fillText('Awesome!', 0, 100)

  return c.res({
    action: '/action',
    image: canvas.toDataURL('image/png'),
    intents: [
      <TextInput placeholder="Enter custom fruit" />,
      <Button value="apples">Apples</Button>,
      <Button value="oranges">Oranges</Button>,
      <Button value="bananas">Bananas</Button>,
      status === 'response' && <Button.Reset>Reset</Button.Reset>,
    ],
  })
})
```

**Comment by ericjuta** [comment]
yup can confirm recent release fixed it
well not with the `<img src={dataUrl} />` as it was working before but yes without the tag
