### ISSUE TITLE
Wrangler environment empty in local

### ISSUE THREAD

**Issue by madroneropaulo** [wevm/frog-archived#124]
### Describe the bug

when working locally I don't have access to the bindings defined in wrangler.toml. If `frog dev` I get
`console.log('env', c.env); // {}`
If I run `"wrangler dev src/index.tsx"`
`console.log('env', c.env); // {ENV_VAR: 'test', FRAMES_BUCKET: R2Bucket}`... etc, all the bindings

### Frog Version

0.5.5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by madroneropaulo** [comment]
Also, it'd be nice if we could pass wrangler flags like '--remote' to the dev command all within frog.

**Comment by tmm** [comment]
Works for me. Can you try again with the latest Frog and report back? If it still doesn't work for you, please attach a minimal reproduction.

**Comment by madroneropaulo** [comment]
@tmm Unfortunately still not working. Using 0.8.0
So I'm talking about wrangler bindings that are supposed to be discoverable in c.env.BINDING_NAME
Steps to reproduce:
1. npm init frog
2. select "cloudflare workers"
3. Uncomment the lines in wrangler.toml
```
[vars]
MY_VARIABLE = "production_value"
```
4. run `npm i` and `npm run dev`
5. in a POST action console log c.env

It's empty. 
What's expected:
if instead of step 4 you run `npm run wrangler:dev` and console log c.env it actually HAS the MY_VARIABLE and all the bindings.

Also, this is only locally. When deployed to prod the bindings ARE there, so I'm just constantly deploying to prod and debugging there insted of using the dev tools

**Comment by tmm** [comment]
Works fine for me

https://github.com/wevm/frog/assets/6759464/02dba928-7fc8-42d8-9c9d-f41f2125a120

**Comment by sammdec** [comment]
fwiw im experiencing the same behaviour, c.env is an empty object when using `frog dev` but when using `wrangler dev` it works fine. Im using the latest version of frog `0.8.6`.

**Comment by sammdec** [comment]
@tmm the odd thing im noticing in your video repro above is that the terminal session thats running looks very different to the terminal view I see when I run `frog dev`, in the video it looks more similar to the wrangler UI

**Comment by sammdec** [comment]
Id be interested in seeing what you have in the code in that example for the dev tools setup because when im trying to run it through wrangler i cant get the dev tools to load in

**Comment by madroneropaulo** [comment]
@sammdec yeah he's running wrangler:dev that's why the port is 8787. Can you try to run npm run wrangler:dev and try the frames debugger at http://localhost:8787/dev? it may work.

**Comment by sammdec** [comment]
Yeah tried that but couldn't get the assets needed for the debugger to load so assuming there is some devtools() config I need to tweak

**Comment by tmm** [comment]
> c.env is an empty object when using frog dev

`c.env` is only populated with the worker context when running wrangler. https://github.com/honojs/hono/issues/799#issuecomment-1380079254

> Id be interested in seeing what you have in the code in that example for the dev tools setup

It's the code from the [Cloudflare Worker template](https://github.com/wevm/frog/tree/main/templates/cloudflare-worker) (plus the logging to the console).

**Comment by sammdec** [comment]
Ah gotcha ok yeah that makes sense then. Was strange I couldn't get the frog dev Ui to load though
