### ISSUE TITLE
lz.decompressFromEncodedURIComponent corrupts output

### ISSUE THREAD

**Issue by m4nuC** [wevm/frog-archived#132]
### Describe the bug

This seems to happen mostly when an emoji is present in the string but not only. 

Here is an example error message:

`Failed to load dynamic font for ₿◨ . Error: Error: Failed to download dynamic font. Status: 400`

Here  ₿◨ shows up even though it's not present in the original JSX. 

I've tried using gzip instead and it fixes the issue but produce a too large URL for proper browser support 

### Frog Version

0.5.5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by jxom** [comment]
How do I reproduce?

**Comment by m4nuC** [comment]
It's tricky. I'll try to catch a failing image and post the JSX. 
Overall I am not sure `lz.decompressFromEncodedURIComponent` is intended for these usecase

**Comment by jxom** [comment]
Emojis seem to render fine for me.

**Comment by jxom** [comment]
I managed to reproduce this issue with the "₿" symbol. This symbol is unable to be rendered with the Satori built-in fonts, so it's not an issue with encoding/decoding URI parameters.

**Comment by m4nuC** [comment]
Yes the issue is that ₿ and a plethora of other weird symbols will show up after decoding string that did not originally contains those symbols. I should have saved some example. Will look for those

**Comment by m4nuC** [comment]
unfortunately I didn't. I will keep an eye for them.

I would however recommend using a different pattern to render images as passing the JSX via a URL will become problematic. eg. if the JSX use large SVG or Base64 encoded images the URL will become too long for most web browser to support it correctly

**Comment by jxom** [comment]
Farcaster team thinking of alternate ways to render frames, which will allow us to avoid encoding/decoding altogether: https://warpcast.notion.site/Faster-Frames-f5f3904aa1c84d41ba2f9660604c48cb?pvs=4
