### ISSUE TITLE
Dev tools lack support for query parameters

### ISSUE THREAD

**Issue by maurelian** [wevm/frog-archived#141]
### Describe the bug

I wanted to build a frame that would dynamically generate text from the query params, I did and it's neat. Thanks for your framework, it's awesome.

However in the process of doing this, I noticed that your dev tools don't allow entering a custom URL.

### Link to Minimal Reproducible Example

https://banner-frame.vercel.app/api/dev

### Steps To Reproduce

Basically, my frame relies on query params. Here is an example of it working properly: https://warpcast.com/maurelian.eth/0x6ad5f98a

But I was unable to test using the frog dev tools because of the limitation.

### Frog Version

0.5.7

### TypeScript Version

5.4.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by floAr** [comment]
Not sure if that is a possible solution for you, but your could use route parameters instead:
https://frog.fm/concepts/routing#path-parameters

Your frame route would be something along those lines:
`https://banner-frame.vercel.app/api/:color/:text`

**Comment by maurelian** [comment]
Interesting, this could probably work.... I assume that the URL escaping the same in the path as in the query string?

**Comment by tmm** [comment]
Will fix this

**Comment by tmm** [comment]
Works fine for me.

https://banner-frame.vercel.app/api/dev?text=frog%20%F0%9F%90%B8&color=green
