### ISSUE TITLE
Inconsistent behavior with Component rendering

### ISSUE THREAD

**Issue by zerohex-eth** [wevm/frog-archived#145]
### Describe the bug

I've encountered an issue where similar pieces of code produce different behaviors when rendering components. The direct usage of a custom component works as expected, but when the custom component is wrapped it doesn't render. 

### Link to Minimal Reproducible Example

https://github.com/Dom-Mac/minimal-repro-frame-components-issue/blob/main/src/index.tsx

### Steps To Reproduce

Let's say there is a custom component as 

```
function FrameContainer({ children }: { children?: JSX.Element | string }) {
  return (
    <div style={{...}}>
      {children}
    </div>
  )
}
```

Using it in this way works as expected
```
...
image: <FrameContainer>It works!</FrameContainer>,
...
```

Let's define a new component as 
```
function Issue() {
  return <FrameContainer>Issue here!</FrameContainer>
}
```

The following renders a black image
```
...
image: <Issue/>,
...
```

Full code in the [repo](https://github.com/Dom-Mac/minimal-repro-frame-components-issue/blob/main/src/index.tsx)

### Frog Version

0.6.0

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by jxom** [comment]
fixed
