### ISSUE TITLE
Docs claim `value` is a prop of `Button.Transaction` in docs but isn't in source code

### ISSUE THREAD

**Issue by stevedylandev** [wevm/frog-archived#146]
### Describe the bug

In the documentation for Frog it says that `value` is one of the props for `Button.Transaction`: https://frog.fm/intents/button-transaction#value-optional

However in the current source code it is not there: https://frog.fm/intents/button-transaction#value-optional

I think having this prop would be really beneficial for handling transaction amounts via Button values that can be handled in `app.transaction` routes! 

### Frog Version

0.6.0

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by jxom** [comment]
Updated docs. You can probably just pass query params to the `target` instead for this.

**Comment by touka-0** [comment]
@jxom The doc issue still exists. I got trapped by it here... https://github.com/wevm/frog/blob/frog%400.11.5/site/pages/reference/frog-transaction-context.mdx#buttonvalue
