### ISSUE TITLE
Create shared components for Images

### ISSUE THREAD

**Issue by chuckstock** [wevm/frog-archived#150]
### Describe the bug

Maybe this isn't possible but I wanted to create shared components for rendering images, which i was able to do without frog but now i just get internal server errors.

You can see how horsefacts does it in the floor sweep repo:
Shared Component
https://github.com/horsefacts/floor-sweep-frame/blob/main/src/app/components/Card.tsx
Using component 
https://github.com/horsefacts/floor-sweep-frame/blob/main/src/app/api/images/bestListing/route.tsx

However if I do this same thing, it won't work. Might have to do with how hono processes these routes, but just wanted to see if there was a potential fix for this.

### Frog Version

0.6.1

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by jxom** [comment]
Can you provide a minimal reproducible example? Can’t reproduce.

**Comment by jxom** [comment]
Please reopen with a minimal reproduction
