### ISSUE TITLE
Button.Mint not working for me

### ISSUE THREAD

**Issue by 0x94t3z** [wevm/frog-archived#152]
### Describe the bug

I'm using `Vercel` -> https://frog.fm/platforms/vercel and use `Button.Mint` -> https://frog.fm/intents/button-mint to create mint button using `Warps`. I tested on `local` it's work, it's showing the button.

<img width="551" alt="Screenshot 2024-03-14 at 5 47 06 PM" src="https://github.com/wevm/frog/assets/52822242/d967d315-f1b2-463f-b1b8-c47127388c3b">

But, if I tested it on dev frames (https://warpcast.com/~/developers/frames) it's not mint using `Warps` and the button changed into `Button.Link` (like action link).

<img width="535" alt="Screenshot 2024-03-14 at 5 50 24 PM" src="https://github.com/wevm/frog/assets/52822242/90a58268-a60d-4d05-b538-cfcd9629ae58">

### Link to Minimal Reproducible Example

https://github.com/Mr94t3z/minters-leaderboard-frame

### Steps To Reproduce

```JS
app.frame('/', (c) => {
  currentPage = 1; // Reset currentPage when navigating to the initial frame
  return c.res({
    action: '/leaderboard',
    image: '/nouns_film.jpg',
    intents: [
      <Button action="/leaderboard" value="leaderboard page">Leaderboard 📊</Button>,
      <Button.Mint
        target="eip155:7777777:0x060f3edd18c47f59bd23d063bbeb9aa4a8fec6df:69420"
      >
        Mint
      </Button.Mint>
    ],
  });
});
```

### Frog Version

frog@v0.6.0

### TypeScript Version

5.4.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by dalechyn** [comment]
Repro link is broken, shows 404.

**Comment by dalechyn** [comment]
Validator doesn't recognize mint button, it's Warpcast's issue.
![image](https://github.com/wevm/frog/assets/35642018/7b4d821d-8bb2-4efc-8b68-921dd1581a87)
![Screenshot 2024-03-14 at 13 37 23](https://github.com/wevm/frog/assets/35642018/1406fb9b-edd6-486c-8d8c-bce35c45b831)
