### ISSUE TITLE
deriveState doesn't work for initial render

### ISSUE THREAD

**Issue by ggomaeng** [wevm/frog-archived#182]
### Describe the bug

What I expect is `deriveState` to log `hello` in the console. However, it doesn't get logged.

### Steps To Reproduce

```ts
app.frame('/', async (c) => {
  c.deriveState(() => {
    console.log('hello!'); // this doesn't get called
  });
  return c.res({
    imageAspectRatio: '1:1',
    browserLocation: 'https://mint.club',
    image: 'https://i.imgur.com/7Sww7lT.gif',
    intents: [
      <Button action="/erc20">🪙 Deploy ERC-20</Button>,
      <Button action="/erc1155">🖼️ Deploy ERC-1155</Button>,
    ],
  });
});
```

### Frog Version

0.7.4

### TypeScript Version

5.3.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by ggomaeng** [comment]
Could be related:

![image](https://github.com/wevm/frog/assets/18402191/f72d0fa4-fe84-4f99-a3ed-4c0741ae105c)

**Comment by jxom** [comment]
`deriveState` derives state based on the previous frame. The initial frame has no previous frame, and uses the `initialState` defined on the `Frog` instance.

**Comment by ggomaeng** [comment]
> `deriveState` derives state based on the previous frame. The initial frame has no previous frame, and uses the `initialState` defined on the `Frog` instance.

how would one update the initialState dynamically in the root frame?

Could I do something like
```ts
previousState.someDynamicVariable = { ... }
```

**Comment by jxom** [comment]
Should work!
