### ISSUE TITLE
Bun app scaffolding fails

### ISSUE THREAD

**Issue by bstchow** [wevm/frog-archived#186]
### Describe the bug

https://frog.fm/platforms/bun

Instructions for scaffolding a Bun app seem to fail out of the box due to an import issue with @hono/node-server

"TypeError: Class extends value undefined is not a constructor or null
    at /node_modules/@hono/node-server/dist/index.mjs:8:15"

### Link to Minimal Reproducible Example

https://frog.fm/platforms/bun

### Steps To Reproduce

1. `bunx create-frog -t bun`
2.  Create "hello"
3. `cd ./hello`
4. `bun install` 
5.  Note "warn: incorrect peer dependency "valibot@0.30.0"
6. `bun run dev`

### Frog Version

0.7.7

### TypeScript Version

5.4.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by dalechyn** [comment]
@bstchow,

> Create "hello"
cd ./hello

What is meant by that? I repeated other steps and it works as expected.

**Comment by bstchow** [comment]
@dalechyn I meant create an app named "hello" when prompted by `bunx create-frog -t bun`

**Comment by dalechyn** [comment]
> @dalechyn I meant create an app named "hello" when prompted by `bunx create-frog -t bun`

can you please try the same approach again? can't reproduce.

**Comment by dalechyn** [comment]
Considering this as stale now, please re-open if issue still exists!
