### ISSUE TITLE
Validation fails if protocol is different (http:// & https://)

### ISSUE THREAD

**Issue by sammdec** [wevm/frog-archived#205]
### Describe the bug

In warpcast when adding a url e.g caststorage.com without the protocol it converts it to http://caststorage.com. When a frame shares that same url, it throws an error similar to https://github.com/wevm/frog/issues/180 because the protocol differs. 

### Link to Minimal Reproducible Example

https://warpcast.com/~/developers/frames?url=http://caststorage.com

### Steps To Reproduce

Got to url above, click tx button and see error

### Frog Version

0.7.13

### TypeScript Version

^5.4.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by jxom** [comment]
Does your host/reverse proxy pass a `x-forwarded-proto` header?

**Comment by sammdec** [comment]
What's the best way to find out (I'm using vercel)?

**Comment by dalechyn** [comment]
tested it, doesn't seem to be an issue now. warpcast adds https automatically.
