### ISSUE TITLE
validateFrameEmbed 400 - Frame image error: Invalid ContentType

### ISSUE THREAD

**Issue by allemanfredi** [wevm/frog-archived#220]
### Describe the bug

I'm loading an image from IPFS but when i try to test the frame within the Warpcast validator i get this error:

validateFrameEmbed 400 - Frame image error: Invalid ContentType: 'text/html; charset=UTF-8'.

### Frog Version

0.8.0

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by tmm** [comment]
Please add a minimal reproduction.
