### ISSUE TITLE
out of memory when frog dev recursively navigates directories in user home

### ISSUE THREAD

**Issue by christopherwxyz** [wevm/frog-archived#228]
### Describe the bug

when running `frog dev` outside the project directory, the terminal will cause permissions to flag as devtools works its way down the disk. eventually this will fail as it exhausts memory.

![image](https://github.com/wevm/frog/assets/362387/5011fcaa-5d1f-4187-80a0-abffa09f07a6)

![image](https://github.com/wevm/frog/assets/362387/1abe873a-9d2c-4738-aad0-16d5b318ff07)

### Steps To Reproduce

run `frog dev` in a user home directory

### Frog Version

0.7.6+

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by dalechyn** [comment]
> perhaps devtools could detect if the current folder has a package.json to start in watch mode, and disable watch mode totally if not

**Comment by tmm** [comment]
@dalechyn if `injectClientScript` is `false`, then devtools are running in standalone mode so watch can be disabled. PR welcome!

https://github.com/wevm/frog/blob/main/src/cli/commands/dev.ts#L28
