### ISSUE TITLE
Wrangler Deploy Fails After Adding FrogUI

### ISSUE THREAD

**Issue by earth2travis** [wevm/frog-archived#240]
### Describe the bug

Receiving Cloudflare error `workers.api.error.script_too_large [code: 10027]` after adding FrogUI

### Link to Minimal Reproducible Example

[TypeScript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgIQK4xhAdgGjgMSggHM4BfOAMyJDgHJqS6BuAKFElkRQgA88AEgFMAhgBNgWYngBqAZRgiAxgGs8ANxFQAzuSo16AOgD0qYIYBW2lu3DR4SMUPWYIAG10VGtBkWLGndRsOe25tISh1IQURGGAlPW96Rn9wyKEAWm1FOKUbY2M4EK4kLCEATywtRINfEmMAC1QAI2tWViFeTnglbGy4ETAwOABeODKAdwI-AAoEVjg4ZqIJtIAZCCVY4GwALnpjOhwFuAK4OVQht3KBuAEWuEw4ISrmtyF9ERAPqKhgSni22whhOZyazX2ZUqWjmAzAwAA0hV9nQAHIAUQAmqiAIIAJQA+vg8QB5ADiRIAsnRyABKE5mfZITQ6cjHMi0wzUL5CGZ0Q54BIjAB8iBOUCEMFQUCwcCUhgl2jmJ0WyjiewObhI2COKqKIBExCE+xmesWAB5kHwzYs4MQVjbVW5gMQsAJoMAAF7YRRuEYAIiULxgEX9joGztdMgiuREfsDwdD4eayhU9ogqCwYgAwu5oAGU6p05mxGHbeWltAnFBc1qoAGJg1gCGyxXFs0qxEAOrAMQwBoBgBsrbbYHEEikAYAzAAmEe24Xh83yRSqRdt8vm4TiSSkbReoRDgAs-uFcgacbccC7HwACm4RDcRNMeQB+c3GbcT4jrjcflepr+m7GFavBAXAtLHOWkghlgMDaPsADalroJgsqaG4qCHv6YAPuUp73o+H5oBg2DCgAulBdJsBybCsL0WD9MA2jZlqqBiJQD4Sl20AqBEoyPOUYBCBAlBysoDRCLoACEIxjHQJZCACZRiMEYkzMxrEZhxXFCDxUB8VAtJiosDH9GkUQxLkJJgOqjECUgRAQDAKImEccAGlg-xSS5iAUGQbCqkMhioOEfLGAAVO5FnRDk8QzDFVnxDZdnaLStKBXAgSuB4MyDGAeBICI2jhPBt6xA0KLGCk0URJZcVKHgiUNSlOz2bRrAUEIHgfPMizZRA7hKvlhVwM12wJB1ZDtJ03RZUpIioG48D5WwQA)

### Steps To Reproduce

Trying to get 🐸 working with [Cloudflare Workers](https://frog.fm/platforms/cloudflare-workers)

```bash
pnpm create frog -t cloudflare-worker
```

In `index.tsx` changed:

```tsx
const manifest = await import('__STATIC_CONTENT_MANIFEST')
const serveStaticOptions = { manifest, root: './' }
```

to:

```tsx
const serveStaticOptions = { root: './', manifest: {} };
```

Added the top level `main` field to `workers.toml`:

```toml
main = "workers-site/index.js"
```

```bash
pnpm wrangler deploy --minify src/index.tsx
```

And it successfully deployed:

```bash
Total Upload: 2334.26 KiB / gzip: 831.76 KiB
```

Then I added `ui.tsx`, imported it, and added some styles in `index.tsx`

```tsx
import { Box, Heading, VStack, vars } from './ui.js';
```

Attempted to deploy the updates:

```bash
pnpm wrangler deploy --minify src/index.tsx
```

And it is failing with the following:

```bash
▲ [WARNING] We recommend keeping your script less than 1MiB (1024 KiB) after gzip. Exceeding this can affect cold start time. Consider using Wrangler's `--minify` option to reduce your bundle size.

▲ [WARNING] Here are the 5 largest dependencies included in your script:

- node_modules/.pnpm/frog@0.8.1_hono@4.2.3/node_modules/frog/_lib/ui/icons.js - 1841.18 KiB
- node_modules/.pnpm/workers-og@0.0.24/node_modules/workers-og/dist/resvg-LFIOYO65.wasm - 1341.69 KiB
- node_modules/.pnpm/workers-og@0.0.24/node_modules/workers-og/dist/index.js - 400.18 KiB
- node_modules/.pnpm/workers-og@0.0.24/node_modules/workers-og/dist/yoga-ZMNYPE6Z.wasm - 86.58 KiB
- node_modules/.pnpm/@scure+bip39@1.2.1/node_modules/@scure/bip39/esm/wordlists/korean.js - 71.91 KiB

If these are unnecessary, consider removing them

✘ [ERROR] A request to the Cloudflare API (/accounts/4e1a03d9fee3ff0defb22eb9feb2c42e/workers/scripts/frog-template) failed.

workers.api.error.script_too_large [code: 10027]
```

```bash
Total Upload: 4185.50 KiB / gzip: 1082.08 KiB
```

### Frog Version

0.8.1

### TypeScript Version

5.4.5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by waptik** [comment]
I can confirm the existence of this bug as I'm also getting similar errors:

```sh
$ bun run wrangler:deploy
$ wrangler deploy --minify src/index.tsx
 ⛅️ wrangler 3.50.0
-------------------
Fetching list of already uploaded assets...
Building list of assets to upload...
 = icon.6207b966a9.png (already uploaded icon.png)
Skipped uploading 1 existing asset.
↗️  Done syncing assets
Total Upload: 4228.45 KiB / gzip: 1100.45 KiB
▲ [WARNING] We recommend keeping your script less than 1MiB (1024 KiB) after gzip. Exceeding this can affect cold start time. Consider using Wrangler's `--minify` option to reduce your bundle size.


▲ [WARNING] Here are the 5 largest dependencies included in your script:

  - node_modules/frog/_lib/ui/icons.js - 1841.18 KiB
  - node_modules/workers-og/dist/resvg-LFIOYO65.wasm - 1341.69 KiB
  - node_modules/workers-og/dist/index.js - 400.18 KiB
  - node_modules/workers-og/dist/yoga-ZMNYPE6Z.wasm - 86.58 KiB
  - node_modules/@scure/bip39/esm/wordlists/korean.js - 71.91 KiB
  If these are unnecessary, consider removing them



✘ [ERROR] A request to the Cloudflare API (/accounts/[REDACTED]) failed.

  workers.api.error.script_too_large [code: 10027]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose


error: script "wrangler:deploy" exited with code 1
error: script "deploy" exited with code 1
```

**Comment by carlaiau** [comment]
Same here, on Cloudflare workers specifically

**Comment by zerokarafont** [comment]
upgrade workers to paid plan, max 10M size, solved my problem
