### ISSUE TITLE
missing dep @iconify/utils

### ISSUE THREAD

**Issue by 0xbid** [wevm/frog-archived#260]
### Describe the bug

I think `main` branch of frog has a dependency on `@iconify/utils`, but it is not specified so this you can't install frog

### Link to Minimal Reproducible Example

NA

### Steps To Reproduce

not possible

### Frog Version

main

### TypeScript Version

main

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by jxom** [comment]
Unsure what you mean. Works fine for me.
