### ISSUE TITLE
debugger not working with frog UI

### ISSUE THREAD

**Issue by madroneropaulo** [wevm/frog-archived#264]
### Describe the bug

Frog debugger not working with frog UI (the background is black and so is the text no matter what I put as a background color or text color).

### Steps To Reproduce

`npm init frog`
choose default
create a `ui.ts` file with this content
```
import { createSystem } from 'frog/ui'
export const { Box, Heading, Text, VStack, vars } = createSystem()
```
replace the initial image code (the generated by npm init frog) with the base example provided by [frog UI docs](https://frog.fm/ui/getting-started).

```
<Box
            grow
            alignVertical="center"
            backgroundColor="background"
            padding="32"
        >
            <VStack gap="4">
                <Heading>FrogUI 🐸</Heading>
                <Text color="text" size="20">
                    Build consistent frame experiences
                </Text>
                <Text color="text" size="20">
                    with Frog.</Text>
        </VStack>
      </Box>
```

### Frog Version

0.8.4

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

### Anything else?

it's definitely a UI issue because it works fine if I just do regular `<div style={...}>`

**Comment by dalechyn** [comment]
was also able to reproduce it

**Comment by tmm** [comment]
Works fine for me. Closing until a minimal reproduction is attached.

**Comment by madroneropaulo** [comment]
https://github.com/madroneropaulo/frame-bug here's a repo.
Steps:
1.npm install
2.` npm run dev` // the debugger doesn't show anything
2.  `npm run wrangler:deploy` // the deployed version looks like there's no UI at all. Here's the deployed URL https://frog-template.pinata-marketing-enterprise.workers.dev

**Comment by dalechyn** [comment]
> https://github.com/madroneropaulo/frame-bug here's a repo. Steps: 1.npm install 2.` npm run dev` // the debugger doesn't show anything 2. `npm run wrangler:deploy` // the deployed version looks like there's no UI at all. Here's the deployed URL https://frog-template.pinata-marketing-enterprise.workers.dev

```ts
export const app = new Frog({
  ui: {vars}
})
```

this was missing.
![Screenshot 2024-05-07 at 00 21 00](https://github.com/wevm/frog/assets/35642018/63f07ec6-00bf-4c41-ac69-b618fa63ac42)
