### ISSUE TITLE
/api/dev shows blank screen in nextjs when initialised using npm

### ISSUE THREAD

**Issue by 0xRadioAc7iv** [wevm/frog-archived#270]
### Describe the bug

On initialising a frog project in next project using 'npm init frog -- -t next', when i try to hit 'http://localhost:3000/api/dev', it shows 404 not found, but the issue is resolved when intialised using pnpm.

### Frog Version

0.8.5

### TypeScript Version

5.4.5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by dalechyn** [comment]
cannot reproduce, works for me.

please add a minimal reproducible example.

**Comment by 0xRadioAc7iv** [comment]
Yep, it works. I don't know what went wrong last time. My bad.
