### ISSUE TITLE
Image created using frog cannot be validated nor casted in warpcast

### ISSUE THREAD

**Issue by roberpkr** [wevm/frog-archived#275]
### Describe the bug

Warpcast validation is errored:

19:21:01
validateFrameEmbed 400 - Frame image error: Invalid ContentType: 'text/html; charset=UTF-8'.
Total
1235ms

If you try to cast it directly , the image can not be loaded

![image](https://github.com/wevm/frog/assets/106393494/01bd4476-d84e-4306-a880-6143e801e2fb)

I am not an expert but I think that frog is not properly parsing the html to be 100% compliant with the protocols.

### Steps To Reproduce

1. Create a new frog project using node template
2. Publish the service using any PaaS Platform (I have tested prublishing from my own cloud server, with cloudfront and without it and same results)
3. Put the url in the https://warpcast.com/~/developers/frames  -> you could receive the Frame image error
4. Try to cast it   -> you could receive the Image Failed to load error

### Frog Version

0.8.6

### TypeScript Version

3.12.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

### Anything else?

I started using 0.8.5 and i could not cast any frame yet. Last version, 0.8.6,has the same behaviour.
Thank you!

**Comment by madroneropaulo** [comment]
https://github.com/wevm/frog/pull/271 maybe related? it was the same error I was getting when it was trying to fetch an image from within. Not sure if this is already in prod? https://github.com/wevm/frog/pull/272

**Comment by dalechyn** [comment]
tested it out with node template on a vps.

are you sure you're testing against a correct link?

if you're using template next or vercel, you have to add `/api` suffix.

if the issue still exists, please add a fully reproducible example that I can clone and reproduce.
closing this but feel free to reopen.

**Comment by roberpkr** [comment]
hi, i am bit crazy with this topic. I am not able to do it working..



Steps to reproduce:
1. npm init frog -- -t node
2. In the project, npm run serve
3. Server is running in port 3000 -> http://65.108.227.172:3000  ( i am going to try to keep it up for testing purposes)
4. Go to https://warpcast.com/~/developers/frames?url=http%3A%2F%2F65.108.227.172%3A3000 and try to verify it
5. Cannot cast it
![image](https://github.com/wevm/frog/assets/106393494/da8d37b6-ea22-464c-94d7-3d186bf864bc)

Config
node : v.18.14.1
{
  "name": "try7frognode",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "frog dev",
    "serve": "tsx src/index.tsx"
  },
  "dependencies": {
    "@hono/node-server": "^1",
    "hono": "^4",
    "frog": "latest"
  },
  "devDependencies": {
    "@types/node": "^20.11.17",
    "tsx": "^3.12.2"
  }
}
