### ISSUE TITLE
npm template frame image isn't working in devtools

### ISSUE THREAD

**Issue by dalechyn** [wevm/frog-archived#276]
### Describe the bug

> I keep getting this broken image in devtools.
> 
> I'll scaffold a new project, devtools displays the frame fine.
> I can update button text and other logic fine, but if I change even one character in the text div element, the background gets a broken image logo.
> Multiple pages correctly update the buttons, but maintain the broken image.
> 
> I can push it to a vercel app, and use it in the Warpcast Frame Validator and it shows correctly, just not in devtools.
>
![image](https://github.com/wevm/frog/assets/35642018/aadb24c2-cd2c-4e07-8083-45f5287cd1c5)

### Link to Minimal Reproducible Example

https://discord.com/channels/1156791276818157609/1212219334370529370/1232045258288922728

### Frog Version

0.8.6

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by tmm** [comment]
Closing for now. Happy to look into more if there's a minimal reproduction with clear reproduction steps.
