### ISSUE TITLE
ERC20 Support?

### ISSUE THREAD

**Issue by titusdecali** [wevm/frog-archived#277]
### Describe the bug

In the docs I see details on how to mint and send normal ETH, however I'm curious if you support typical transaction payloads for sending ERC20?

I've tried `c.send`, but it seems specifically designed for ETH.

In the Farcaster Frames Spec, I see they have a `tx`, is the same as `c.send` in frog?

Looking at the types for `c.res -> data` I get `You can't pass property data to type TransactionParameters.` and the type name is `EthSendTransactionParams`.  Typically I would pass the transaction data here, but it doesn't seem to exist.

Alternatively, is there a way to directly interact with the provider which might allow for more complex transactions?

Is it even possible to start an ERC20 transaction?

### Frog Version

0.8.6

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by tmm** [comment]
Check out [`c.contract(...)`](https://frog.fm/reference/frog-transaction-response#contract-transaction-ccontract)
