### ISSUE TITLE
Image created using node frog template cannot be validated nor casted in warpcast

### ISSUE THREAD

**Issue by roberpkr** [wevm/frog-archived#291]
### Describe the bug

Warpcast validation is errored:

19:21:01
validateFrameEmbed 400 - Frame image error: Invalid ContentType: 'text/html; charset=UTF-8'.
Total
1235ms

If you try to cast it directly , the image can not be loaded

![image](https://github.com/wevm/frog/assets/106393494/f44dad09-0461-40bf-8669-1bba435eaead)

### Link to Minimal Reproducible Example

http://65.108.227.172:3000

### Steps To Reproduce

npm init frog -- -t node
In the project, npm run serve
Server is running in port 3000 -> http://65.108.227.172:3000/ ( i am going to try to keep it up for testing purposes)
Go to https://warpcast.com/~/developers/frames?url=http%3A%2F%2F65.108.227.172%3A3000 and try to verify it
Cannot cast it
![image](https://github.com/wevm/frog/assets/106393494/c8e4c0d1-395b-48e0-ab56-78bd9d8e74ac)

Config
node : v.18.14.1
{
"name": "try7frognode",
"private": true,
"type": "module",
"scripts": {
"dev": "frog dev",
"serve": "tsx src/index.tsx"
},
"dependencies": {
"@hono/node-server": "^1",
"hono": "^4",
"frog": "latest"
},
"devDependencies": {
"@types/node": "^20.11.17",
"tsx": "^3.12.2"
}
}

### Frog Version

0.8.7

### TypeScript Version

3.12.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

### Anything else?

I started using 0.8.5 and i could not cast any frame yet. Last version, 0.8.7,has the same behaviour.
Thank you!

**Comment by dalechyn** [comment]
https://warpcast.com/dalechyn.eth/0xfdfa889b

**Comment by dalechyn** [comment]
@roberpkr, I'm closing this issue as it might be WC bug itself, back when I tested your URL all the meta tags were accessible.

> https://warpcast.com/dalechyn.eth/0xfdfa889b

Let's try getting a response from FC team. At the meantime, I'd advise to somehow not use port in your frame url.
