### ISSUE TITLE
DevTools: incorrect parsing behavior for image URLs from frame responses

### ISSUE THREAD

**Issue by darrylyeo** [wevm/frog-archived#299]
### Describe the bug

When using `frog`'s standalone DevTools, `og:image` and `fc:frame:image` URLs containing `&` gets parsed as `&amp;` when returned from frame action POST responses.

<img width="1086" alt="Screenshot 2024-05-03 at 14 28 30" src="https://github.com/wevm/frog/assets/13970789/bcd0004d-41db-4013-ad03-fce2b8d79cc0">

### Steps To Reproduce

* Make a (non-`frog`) frame with a button
* In the frame response, return `https://example.com?a=1&b=2&c=3` as the `fc:frame:image` URL.
* Start `frog` dev tools in standalone mode and navigate.

### Frog Version

0.9.0

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by dalechyn** [comment]
looking at the tests, this is expected in frog as it decodes `amp`s properly.

@tmm, is standalone devtools purpose includes supporting debugging of non-frog frames? if no, this can be closed as won't fix.

**Comment by tmm** [comment]
Standalone mode is supposed to work on non-frog frames!
