### ISSUE TITLE
Image created using node frog template cannot be validated nor casted in warpcast

### ISSUE THREAD

**Issue by roberpkr** [wevm/frog-archived#314]
### Describe the bug

Warpcast validation is errored:
https://warpcast.com/~/developers/frames?url=https%3A%2F%2Fframe.cryptodefitracker.com%2F
![image](https://github.com/wevm/frog/assets/106393494/cd6cdf7c-8f55-49a2-941c-8cf096418279)
If you try to cast it directly , the image can not be loaded

### Link to Minimal Reproducible Example

https://frame.cryptodefitracker.com/

### Steps To Reproduce

I started a new node project:
npm run init frog
> node

I set the certificates providing the following config and started serving:

const port = 443
let sslOptions = {
  cert: cert,
  ca: ca, 
  key: key
};
console.log(`Server is running on port ${port}`)

devtools(app, { serveStatic });

serve({
  fetch: app.fetch,
  createServer: createServer,
  serverOptions: {
    key: key,
    cert: cert
  },
  port:port
  
  You can check it at https://frame.cryptodefitracker.com/
  For debugging purposes you can go to https://frame.cryptodefitracker.com/dev
  
  Thanks in advanced!

### Frog Version

0.9.4

### TypeScript Version

3.12.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

### Anything else?

I have this issue from versión 0.8.4 and cannot fix it.
You can reach me to do some tests, 
thank you in advance!!

**Comment by dalechyn** [comment]
From what I see, the initial GET requests are passing fine:
![Screenshot 2024-05-13 at 19 56 43](https://github.com/wevm/frog/assets/35642018/d7b3e4d8-67a8-4d83-a8a5-04c2d2453473)
works in supercast
![Screenshot 2024-05-13 at 19 57 47](https://github.com/wevm/frog/assets/35642018/7b543a20-a26d-4a52-a375-f96195c657a7)
works in warpcast.

Actions (POST requests) seem to work fine both in frog debugger and frames.js debugger.

However, in WC and supercast I'm getting 403/500 respectively.

**Comment by dalechyn** [comment]
Asked @horsefacts for help.
