### ISSUE TITLE
ButtonLink componet  will escape '&' to '&amp;' when the href includes '&'

### ISSUE THREAD

**Issue by zyc8988** [wevm/frog-archived#315]
### Describe the bug

the code is: 
`<Button.Link href="http://a.com?a=1&b=2"></Button.Link>`

and then it will excape the link into 'http://a.com?a=1&amp;b=2', which is invalid when visit 'a.com'

expect:
'&' will be still '&', not '&amp'

### Frog Version

0.9.4

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by hi-nikhil** [comment]
encountering the same issue.
