### ISSUE TITLE
Developer experience improvement: twice api key declaration

### ISSUE THREAD

**Issue by JWMatheo** [wevm/frog-archived#319]
### Describe the bug

I'm using neynar as a hub AND as a middleware.

I have to declare twice my api key and it feels weird.

![image](https://github.com/wevm/frog/assets/88055282/eccf9a90-dca0-4f2e-8a8e-3f5a21307a77)

Suggestion:
- Add a "hub" key into neynar (from frog/middleware)
![image](https://github.com/wevm/frog/assets/88055282/76a8f7f1-db70-4c60-a1fd-0a6cd4686967)

Benefits:
- get rid of one import
- only one api key declaration

### Frog Version

0.9.3

### TypeScript Version

^5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by tmm** [comment]
Something like this could nice.

```ts
import { neynar as neynarHub, NeynarHubParameters } from 'frog/hubs'
import {
  NeynarMiddlewareParameters,
  neynar as neynarMiddleware,
} from 'frog/middlewares'

type CreateNeynarParameters = {
  apiKey: string
  hub?: NeynarHubParameters | undefined
  middleware?: NeynarMiddlewareParameters | undefined
}

function createNeynar(parameters: CreateNeynarParameters) {
  const {
    apiKey,
    hub = { apiKey },
    middleware = { apiKey, features: ['cast', 'interactor'] },
  } = parameters
  return {
    hub: neynarHub(hub),
    middleware: neynarMiddleware(middleware),
  }
}
```

Then,

```ts
const neynar = createNeynar({ apiKey: 'NEYNAR_FROG_FM' })

export const app = new Frog({ hub: neynar.hub })
  .frame('/', (c) => {
    return c.res({ ... })
  })
  .frame('/guess', neynar.middleware, (c) => {
    const { displayName, followerCount } = c.var.interactor || {}
    console.log('interactor: ', c.var.interactor)
    console.log('cast: ', c.var.cast)
    return c.res({ ... })
  })
```

**Comment by tmm** [comment]
Added https://github.com/wevm/frog/commit/1012bd5c85d761f82bae2720ed153b58f5737abe#diff-d8aed8b8464aff240df9199627027c4e74335e52e7fb9a955223756dfd24daa6R210

**Comment by JWMatheo** [comment]
Ty!
