### ISSUE TITLE
NPM->Vercel template has incorrect typings issue

### ISSUE THREAD

**Issue by dalechyn** [wevm/frog-archived#336]
### Describe the bug

Types are borked after making a template with npm+vercel.
![Screenshot 2024-05-27 at 17 49 27](https://github.com/wevm/frog/assets/35642018/688736f5-c3ce-4030-b0e4-725f92251967)

### Link to Minimal Reproducible Example

https://github.com/dalechyn/frog-27may-npm-vercel

### Steps To Reproduce

1. npx create-frog@latest
2. vercel template

### Frog Version

0.11.2

### TypeScript Version

5.0.4

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by AndrewCarneal** [comment]
This same issue occurs when using the "Bootstrap via Vercel" button in the getting started guide: https://frog.fm/getting-started

**Comment by dalechyn** [comment]
Should have been fixed by https://github.com/honojs/hono/pull/2662/commits/5bd2b71709a3e8d28a83c193fb70d7363b65dc85 in https://github.com/honojs/hono/pull/2662. trying to bump hono versions to see if this gets it fixed.
