### ISSUE TITLE
Text align property isn't working within flex container

### ISSUE THREAD

**Issue by scottrepreneur** [wevm/frog-archived#344]
### Describe the bug

Edit: this appears to be specifically when the containing `Box` is set to `display='flex'`

_Appears to occur on both `Text` and `Heading` components._

I am adding `align` to a `Text` component, but it is not being [centered] accordingly, ~~similar to the `Heading` component~~. Applying `textAlign='center'` on the parent works for `Text` but doesn't seem to affect `Heading` in my experience (works, if consistent here).

### Link to Minimal Reproducible Example

will try to add

### Steps To Reproduce

1. Add `Heading` and `Text` component into a `Box` using `display='flex'`
2. Use `align='center'`, text is not aligned
3. Use `textAlign='center'` on the parent `Box`, text is aligned.

### Frog Version

0.11.x

### TypeScript Version

5.4.5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by dalechyn** [comment]
I believe that adding `display='flex'` would shrink elements width to it's min-content, thus the `Box` size would equal `Text`/`Heading`. Does it happen if you add `grow` prop to `Box`?
