### ISSUE TITLE
Frame is requested multiple times per single render.

### ISSUE THREAD

**Issue by dalechyn** [wevm/frog-archived#35]
Reproducible example: https://github.com/dalechyn/mini-repros/tree/main/frog-request-spam
Video: 

https://github.com/wevm/frog/assets/35642018/2568ca23-c0ab-47bb-ad1b-e5dad383482b

frog version: `0.2.1`

**Comment by jxom** [comment]
There are intended to be two requests: one for the frame endpoint, and one for the OG image endpoint. I think the third may be coming as a side-effect from the devtools (we can take a look), but it shouldn't behave this way in production.

**Comment by jxom** [comment]
There is now a [`cycle` property](https://frog.fm/reference/frog-frame-context#cycle) on context which can be used to distinguish between the "main" & "image" render cycles.
