### ISSUE TITLE
Frequent Logouts with Local Debug Frame Tool

### ISSUE THREAD

**Issue by nestorbonilla** [wevm/frog-archived#351]
### Describe the bug

Hi team,

I'm encountering frequent logouts (every couple of hours, although there's no specific time) when using the local debug frame tool, even though I've provided a hub in my app definition:
```
const app = new Frog({
  assetsPath: '/',
  basePath: '/api',
  hub: neynar({ apiKey: process.env.NEYNAR_API_KEY! }),
  verify: process.env.NODE_ENV === 'production'
})
```
I've tried both with and without the verify attribute.
Is there a workaround to prevent these logouts? It's consuming my Warps.

Thanks for looking into this!

### Frog Version

0.11.5

### TypeScript Version

5.4.5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by nestorbonilla** [comment]
Maybe [SIWN](https://docs.neynar.com/docs/how-to-let-users-connect-farcaster-accounts-with-write-access-for-free-using-sign-in-with-neynar-siwn) could help with these logouts? Seems like it might be a smoother way to handle authentication overall.

**Comment by dalechyn** [comment]
Should have been improved with #380. If frequent logouts is still a thing – feel free to reopen.
