### ISSUE TITLE
Button.Link breaks url

### ISSUE THREAD

**Issue by waptik** [wevm/frog-archived#352]
### Describe the bug

So i have this url that has an `&next-page=/path`(a way for softr app to [redirect users to a page after login in](https://docs.softr.io/user-management/pxnkp9H3qyEVMF6XUceqnj/users-tab/5JTzjtbvp8Skemd26A9ho9#use-magic-link) ) but frog generates the url as `https://example.com/magic-authentication?magic-token=xxxxxxxxx&amp;next-page=%2Fpath` instead of `https://example.com/magic-authentication?magic-token=e14c43269d744516986509d1cad8eb76&next-page=%2Fpath` and it's breaking url redirection

### Frog Version

0.8.7

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by dalechyn** [comment]
> Frog Version
> 0.8.7

You're using an outdated version of Frog, I believe this is fixed in https://github.com/wevm/frog/commit/913b0cb6da5de738118d35d767d0168295bc5b2d.

If upgrading doesn't help, please reopen the issue and add a minimal reproducible example.
