### ISSUE TITLE
Image Handler fails to render Frog UI components correctly 

### ISSUE THREAD

**Issue by IlyaSinyugin** [wevm/frog-archived#353]
### Describe the bug

I am trying to use ImageHandler as I run into some errors when using a lot of Frog UI components in a frame. e.g. the frame URL becomes too long and Farcaster fails to load data from it. 

However, when I try to replicate the same components in ImageHandler, the image ends up rendering in a completely different way. 

With ImageHandler:
![image](https://github.com/wevm/frog/assets/44947499/fbfd1b3b-a86d-47d8-ab2c-e9814ee65fc6)

Without ImageHandler:
![image](https://github.com/wevm/frog/assets/44947499/e918023d-e524-4cd8-b3a4-787ea0765ce3)

### Link to Minimal Reproducible Example

https://github.com/IlyaSinyugin/error-replication-powerfeed

### Steps To Reproduce

- Clone the repository 
- `npm install`
- `npm run dev`
- "Check your Power Score" button uses regular Frog UI without ImageHandler, "ImageHandler" button displays the frame when using ImageHandler. 

### Frog Version

0.11.6

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by dalechyn** [comment]
Your `Divider` components are missing `direction="horizontal"`, so they took all the vertical space. I applied the changes and was able to retrieve the frame:

![image](https://github.com/wevm/frog/assets/35642018/5b91077e-9768-4321-86b6-1b1e80d1f53d)

Will think about making `horizontal` the default value for `Divider`.
