### ISSUE TITLE
`export const runtime = 'edge'` breaks frog debugger

### ISSUE THREAD

**Issue by dalechyn** [wevm/frog-archived#36]
### Describe the bug

I've uncommented the `export const runtime = 'edge'` line and the frog debugger crashed.

### Link to Minimal Reproducible Example

https://github.com/dalechyn/mini-repros/tree/main/frog-edge-issue

### Steps To Reproduce

1. Fork the repro.
2. `cd frog-edge-issue && pnpm dev`
3. Navigate to `localhost:3000/api/dev`

### Frog Version

0.2.1

### TypeScript Version

5.0.4

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

### Anything else?

Reproducible video:

https://github.com/wevm/frog/assets/35642018/dd3dc484-2cda-4108-afad-0c2a35396d1b

**Comment by tmm** [comment]
Seems like an upstream Next.js issue since the following works:

```ts
export const config = {
  runtime: "edge",
};
```
