### ISSUE TITLE
The UI changing after I use Image Handler

### ISSUE THREAD

**Issue by 0x94t3z** [wevm/frog-archived#362]
### Describe the bug

1. Without image handler:
```tsx
app.image('/', (c) => {
  return c.res({
    image: (
      <Box
            grow
            alignVertical="center"
            backgroundColor="bg"
            padding="48"
            textAlign="center"
            height="100%"
        >
        <Heading color="red" font="playfair_display" weight="900" align="center" size="64">
            REGEN 🍄 STATS
        </Heading>
      </Box>
    ),
  })
})
```
<img width="550" alt="Screenshot 2024-06-15 at 1 28 45 PM" src="https://github.com/wevm/frog/assets/52822242/62994ab9-5421-4070-88ea-342fef56b652">

2. Using image handler:
```tsx
app.frame('/', async (c) => {

  return c.res({
    title: 'Regen Stats',
    image: `/refreshing-image`,
    
    intents: [
      <TextInput placeholder="Search by username" />,
      <Button action='/stats'>My Stats</Button>,
      <Button value="oranges">Search</Button>,
      <Button.Link href='https://warpcast.com/0x94t3z.eth'>Creator</Button.Link>,
      <Button.Link href={CAST_INTENS}>Share</Button.Link>,
    ],
  })
})

app.image('/refreshing-image', (c) => {
  return c.res({
    imageOptions: {
      headers: {
        'Cache-Control': 'max-age=0',
      },
    },
    image: (
      <Box
            grow
            alignVertical="center"
            backgroundColor="bg"
            padding="48"
            textAlign="center"
            height="100%"
        >
        <Heading color="red" font="playfair_display" weight="900" align="center" size="64">
            REGEN 🍄 STATS
        </Heading>
      </Box>
    ),
  })
})
```

<img width="562" alt="Screenshot 2024-06-15 at 1 29 05 PM" src="https://github.com/wevm/frog/assets/52822242/b73c356d-d52e-4ce2-b697-674537451bb5">

### Link to Minimal Reproducible Example

https://github.com/Mr94t3z/regen-stats

### Frog Version

frog@v0.11.8

### TypeScript Version

4.7.1

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by dalechyn** [comment]
![Screenshot 2024-06-16 at 16 22 52](https://github.com/wevm/frog/assets/35642018/22175f4c-082e-4dde-af31-8711a881681e)
could not reproduce the issue myself, but discovered a bug with `Divider` that sets wrong `direction` when not set explicitly. Had to put `direction="horizontal"` to make the frame appear in the first place.
