### ISSUE TITLE
Fetch get loadGoogleFont error in hono-og

### ISSUE THREAD

**Issue by co-index** [wevm/frog-archived#368]
### Describe the bug

I created a new blank project for next using the pnpm create frog command, but when I started the project I got a error.

### Steps To Reproduce

1.  pnpm create frog
2. pnpm install
3. pnpm dev 
4. open localhost:3000api/dev
<img width="1674" alt="image" src="https://github.com/wevm/frog/assets/89052431/d9a25b86-6fe6-4345-9f4b-fb52d1b17d8b">

I was able to locate the error because I used html tags such as div in the image
<img width="983" alt="image" src="https://github.com/wevm/frog/assets/89052431/e11dd152-b297-47f5-80f1-8232d8c17641">
When I populate images with the local file address, all errors disappear
<img width="1214" alt="image" src="https://github.com/wevm/frog/assets/89052431/7d3cbe2d-1210-4c88-aefc-d7b67f3acd60">

I think it may be because I have opened a vpn in China, but I have rarely encountered such fetch errors.

### Frog Version

0.11.9

### TypeScript Version

5.4.5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by dalechyn** [comment]
please add a repro and i'll be able to take a look at it!
