### ISSUE TITLE
bug: request body is not a valid json on frame rerender

### ISSUE THREAD

**Issue by jacopo-eth** [wevm/frog-archived#37]
### Describe the bug

when satori is used, frame is rerended 3 times #35.

calling `await c.req.json()` yields the expected result only on the first render. on subsequent ones there is no request body, and thus execution reverts due to `SyntaxError: Unexpected end of JSON input`. this breaks the debugger.

note that this error is only triggered when satori is used. if a url is passed in `image` there is a single rerender and everything works as expected.

### Steps To Reproduce

- call `await c.req.json()`
- return a JSX element inside `image`

### Frog Version

0.2.1

### TypeScript Version

5.3.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by jxom** [comment]
Try:

```tsx
const data = c.req.method === 'POST' ? await c.req.json() : {}
```
