### ISSUE TITLE
Can't import `ImageHandler` type

### ISSUE THREAD

**Issue by estarossa0** [wevm/frog-archived#370]
### Describe the bug

Can't import `ImageHandler` type from 'frog'. I get `Module '"frog"' has no exported member 'ImageHandler'` although I can see that it's exported, same thing for `ImageContext` `CastActionHandler` `CastActionContext`
![image](https://github.com/wevm/frog/assets/57002508/ecf1d3c4-d551-4eb7-a6aa-bfc596c483fa)

### Frog Version

0.11.9

### TypeScript Version

^5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by dalechyn** [comment]
fixed in 0.11.10!
