### ISSUE TITLE
Image handler does not receive headers and query from frame handler.

### ISSUE THREAD

**Issue by estarossa0** [wevm/frog-archived#371]
### Describe the bug

when using image handler with frame handler, query and header are not received on the image handler:

```tsx
app.frame("/test", (c) => {
  return c.res({
    image: "/img?key=value",
    headers: {
      key: "value",
    },
  });
});

app.image("/img", (c) => {
  const { req } = c;
  console.log(req.query()); // = { } doesn't have `key` query
  console.log(req.header()); // doesn't have `key` header

  const image = <span />;
  return c.res({
    image,
  });
});
```

### Frog Version

0.11.9

### TypeScript Version

^5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by dalechyn** [comment]
please add a minimal reproducible example.

i tested it and i can see the headers present.

Regarding the query key, those are intentionally cut as frog uses them internally.

Please refer to the usage of Path Parameters to pass arbitrary data in the URL: https://frog.fm/concepts/routing#path-parameters
