### ISSUE TITLE
validateFrameEmbed 400 - Frame image error: Invalid ContentType: 'text/html'.

### ISSUE THREAD

**Issue by oleksandrtarapata** [wevm/frog-archived#378]
### Describe the bug

Hey, I'm implementing little advanced frame fetches data from api and smart contracts. I faced with a problem after deploy to Vercel that my frame doesn't get validated by Warpcast Validator. But on my local Frog Devtools it works good. The error is **validateFrameEmbed 400 - Frame image error: Invalid ContentType: 'text/html'.**.

### Link to Minimal Reproducible Example

https://github.com/limitless-labs-group/limitless-trade-frame

### Steps To Reproduce

Clone repo
Install deps
Try locally with this link http://localhost:3000/markets/0xAEfCa6eC53A3EED5e46d87C55e4c57B77aEe49Ba
Deploy to Vercel and use https://{vercel-deployment-link}/markets/0xAEfCa6eC53A3EED5e46d87C55e4c57B77aEe49Ba for a Validator

or use this link for a Validator https://limitless-trade-frame.vercel.app/markets/0xAEfCa6eC53A3EED5e46d87C55e4c57B77aEe49Ba

### Frog Version

latest

### TypeScript Version

^5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by benbaessler** [comment]
facing the same issue
