### ISSUE TITLE
Properties of Box not inherited by VStack

### ISSUE THREAD

**Issue by waptik** [wevm/frog-archived#406]
### Describe the bug

In the UI docs, it's mentioned that [VStack inherits all the properties of Box](https://frog.fm/ui/VStack#box-properties), which is false.
We can see in https://github.com/wevm/frog/blob/main/src/ui/VStack.tsx#L4-L33, `VStackProps` only picks some props of `Box`

Typescript error:
<img width="426" alt="image" src="https://github.com/wevm/frog/assets/1687551/14974079-e25d-4ae9-9b24-a7a6eea4f49e">

References:
<img width="497" alt="image" src="https://github.com/wevm/frog/assets/1687551/9c621904-c20c-46a6-9ccc-cbf07939ab77">
<img width="684" alt="image" src="https://github.com/wevm/frog/assets/1687551/0a79d56c-42ee-4586-802f-1eebfb9ad749">

### Steps To Reproduce

1. Create a `.tsx` file
2. Copy the code snippet at https://frog.fm/ui/VStack#usage
3. Try adding a `border` or `borderRadius` to  `<VStack gap="8" grow>`
4. Wait for typescript to scream at you

### Frog Version

0.13.1

### TypeScript Version

5.5.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by dalechyn** [comment]
makes sense! will fix it!
