### ISSUE TITLE
Issue with the Preview component after connecting wallet

### ISSUE THREAD

**Issue by kien-ngo** [wevm/frog-archived#416]
### Describe the bug

I have a screen record which should help: https://www.loom.com/share/71ea57ee9fe7458b96ecd98af2e8e65d

Basically for some reason, the `address` from `useAccount` is falsy after I connect my MetaMask, causing an error in the Preview component at this line:

https://github.com/wevm/frog/blob/main/ui/src/components/Preview.tsx#L692

### Link to Minimal Reproducible Example

Check video

### Steps To Reproduce

check video

### Frog Version

0.14.2

### TypeScript Version

^5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

### Anything else?

Happens to Rabby as well, fwiw

**Comment by dalechyn** [comment]
Hi! I was not able to reproduce issue neither with MetaMask nor with Rainbow.

The origin of the issue is weird as there is a check for `account.status === 'connected'`, thus it might be an upstream issue of `wagmi` itself.

Can you add a minimal reproducible example?
