### ISSUE TITLE
Bug in uploading videos and creating of events on the Apple iphone

### ISSUE THREAD

**Issue by Rufusemmanuel** [wevm/frog-archived#438]
### Describe the bug

What is the bug?

POSSIBLE EVENT CREATION BUG:
While trying to create events this is the error detected

Error loading page
Domain: NSURLErrorDomain
Error Code: -1004
Description: Could not connect to the server.

This may be attributed to possible causes like server unavailability, network connection, DNS issues but I think this is highly unlikely the case as the frames for bounty and poll activities work clearly on the same device simultaneously so I suggest it should be checked for possible bugs or errors

VIDEO UPLOAD ERROR:

On the new update while trying to upload videos to the timeline it disappears after clicking the video to upload even when it was selected carefully. This is the case for the iPhone as I tried on another device and same reoccurrence was detected. The device been used is the iPhone 14 Pro Max so compatibility is not a problem

Thanks for looking into this and I hope it makes farcaster better.
![IMG_9232](https://github.com/user-attachments/assets/7983b3a8-ef06-4bc3-9675-605d4f2f5d94)

### Link to Minimal Reproducible Example

Error loading page Domain: NSURLErrorDomain Error Code: -1004 Description: Could not connect to the server.

### Frog Version

5.0.5

### TypeScript Version

5.0.5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

### Anything else?

No

**Comment by dalechyn** [comment]
Not related to Frog – please contact events.xyz or add a min. reproducible example.
