### ISSUE TITLE
Issue with Latest Frog not compiling Next.js -- missing title

### ISSUE THREAD

**Issue by thebreadcat** [wevm/frog-archived#440]
### Describe the bug

run the frog command from the docs ``npm init frog -- -t next`` and it creates a project, cd into it, npm install, then push to vercel immediately.  It fails to deploy.   running "yarn build" or "npm run build" locally then produces this error:

```./app/api/[[...routes]]/route.tsx:7:22
Type error: Argument of type '{ assetsPath: string; basePath: string; }' is not assignable to parameter of type 'FrogConstructorParameters<Env, "/" | "/api", unknown>'.
  Property 'title' is missing in type '{ assetsPath: string; basePath: string; }' but required in type 'Required<Pick<FrameResponse, "title">>'.

   5 | import { handle } from 'frog/next'
   6 |
>  7 | const app = new Frog({
     |                      ^
   8 |   assetsPath: '/',
   9 |   basePath: '/api',
  10 |   // Supply a Hub to enable frame verification.```

Adding a title in to the App declaration fixes the issue.  May need to update the install script.


### Link to Minimal Reproducible Example

https://frog.fm

### Steps To Reproduce

Defined above

### Frog Version

0.15.2

### TypeScript Version

5.5.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

### Anything else?

_No response_

**Comment by tmm** [comment]
Easy first issue for someone. Just need to add `title: 'Frog Frame'` to all the templates.

**Comment by thebreadcat** [comment]
it looks like they were all added 4 days ago but the scripts when you run them to create frog aren't pulling in titles (I did a fresh run for next.js today)

**Comment by dalechyn** [comment]
Can't reproduce. Are you sure you have `frog` up to date? It can be that you have it installed globally and it's outdated.

If still reproducible, please reopen.

https://github.com/user-attachments/assets/4c304aa6-8d7a-4509-8721-ffb6d9a8a53a

![Screenshot 2024-07-27 at 00 41 01](https://github.com/user-attachments/assets/02bcc74f-a982-4144-b11b-03b94e785cb6)
