### ISSUE TITLE
Code breaks on deploy to vercel

### ISSUE THREAD

**Issue by Complexlity** [wevm/frog-archived#45]
### Describe the bug

I have defined a new route on "/" while the frame is on "/api". I want the "/" to render normal HTML while leaving the "/api" route to render the frame. 

This works locally and on stackblitz but does not work when I deploy to vercel. It fails in two ways:
1. The "/" route returns "not-found" when I try to get on the browser. The get('/') path apparently doesn't get built
2. The imported jsx is not built so it is unable to find the "../images/welcome.jsx

Both work locally but when deployed on vercel, it breaks

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/Complexlity/frog-init

### Frog Version

0.21.0

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by Complexlity** [comment]
Issue 2 is similar to this: #30

**Comment by jxom** [comment]
Yeah, unfortunately these are both Vercel Functions limitations:

1. Vercel Functions can only reside under the /api route
2. Vercel Functions cannot import JSX files by default (we are looking into a workaround for this as per #30)
