### ISSUE TITLE
TypeError: Failed to parse URL from ... TypeError: Invalid URL

### ISSUE THREAD

**Issue by christopherwxyz** [wevm/frog-archived#46]
### Describe the bug

Install Frog and Hono using latest Next.js 14 -- bun run dev runs fine without a Hub URL. However, when I provide any URL, it will fail with a type error.

<img width="873" alt="Screenshot 2024-03-01 at 7 43 04 AM" src="https://github.com/wevm/frog/assets/362387/bdb4b47c-68a2-43ba-8127-2b716fcff9b2">

<img width="1402" alt="Screenshot 2024-03-01 at 7 43 30 AM" src="https://github.com/wevm/frog/assets/362387/a4b00eb2-680d-47a3-b4e4-e57100d3ae97">

### Link to Minimal Reproducible Example

bun run dev

### Steps To Reproduce

bun run dev, navigate to `http://localhost:3000/api/dev`, click any button, error is thrown.

<img width="243" alt="Screenshot 2024-03-01 at 7 45 25 AM" src="https://github.com/wevm/frog/assets/362387/38d87241-f086-47cb-be00-48a3b12843f1">

### Frog Version

0.2.4

### TypeScript Version

^5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by christopherwxyz** [comment]
Additionally providing a :2283 URL will fail as well:

```log
cause: HTTPParserError: Response does not match the HTTP/1.1 protocol (Expected HTTP/)
      at Parser.execute (node:internal/deps/undici/undici:8593:19)
      at Parser.readMore (node:internal/deps/undici/undici:8552:16)
      at Socket.onSocketReadable (node:internal/deps/undici/undici:8866:16)
      at Socket.emit (node:events:518:28)
      at emitReadable_ (node:internal/streams/readable:832:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
    code: 'HPE_INVALID_CONSTANT',
    data: '\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\b\x07\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02'
  }```

**Comment by Complexlity** [comment]
I ran into the same issue. The reason is, by default, if you have a `hubApiUrl` while creating a new application, it would try to validate every request. 
You can make the error go way by either 
1. Removing `hubApiUrl` on line 9
2. Signing your farcaster account on the dev route
![image](https://github.com/wevm/frog/assets/105590967/4f7ff345-555a-4295-b71e-8b3ef176b4bd)

**Comment by tmm** [comment]
You can also set [`verify`](https://frog.fm/reference/frog#verify) to `false`.

For more info on frame verification, see https://frog.fm/concepts/securing-frames#silent-verification
