### ISSUE TITLE
bug: undefined is not an object (evaluating 'frameActionBody.address')

### ISSUE THREAD

**Issue by manan19** [wevm/frog-archived#465]
### Describe the bug

```
24 | ////////////////////////////////////////////////////////////////////
25 | // Utilties
26 | export function messageToFrameData(message) {
27 |     const frameActionBody = message.data?.body.value;
28 |     const frameData = {
29 |         address: frameActionBody.address
                      ^
TypeError: undefined is not an object (evaluating 'frameActionBody.address')
      at messageToFrameData (/app/node_modules/frog/_lib/utils/verifyFrame.js:29:18)
      at /app/node_modules/frog/_lib/middlewares/neynar.js:14:27
```

### Frog Version

latest

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by dalechyn** [comment]
Can you please try `frog@0.15.9-fix-wrong-parsing-of-frame-message-for-different-handlers.20240808T230644` and come back with a reply if it fixes your issue?

**Comment by manan19** [comment]
> Can you please try `frog@0.15.9-fix-wrong-parsing-of-frame-message-for-different-handlers.20240808T230644` and come back with a reply if it fixes your issue?

@dalechyn Unfortunately, I cannot test the fix without an elaborate setup. The frame developer that found this issue uses frog + neynar and reported it to us (neynar). I just wanted to pass along the bug report.
