### ISSUE TITLE
How do I sign a simple string?

### ISSUE THREAD

**Issue by 0xrpj** [wevm/frog-archived#482]
### Describe the bug

Currently, signing flow is like such:

```
app.signature('/sign', (c) => {
  return c.signTypedData({
    chainId: 'eip155:84532',
    types: {
      Swamp: [{ name: 'frog', type: 'string' }],
    },
    primaryType: 'Swamp',
    message: {
      frog: 'Hello, world!',
    },
  })
});

```

I want to sign a simple string "Hello, world". How do I do it?

### Frog Version

0.17.1

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by 0xrpj** [comment]
To be clearer, the above way also produces signature. However, the signature produced this way is different than the signature produced in a normal way.

**Comment by dalechyn** [comment]
Hi! Unfortunately only typed signatures are supported in Farcaster Frame Signatures Spec., so you can't just sign a simple string.

I suggest creating a minimal typed data structure.
