### ISSUE TITLE
I think the bot detection is assuming an older version of detect-browser

### ISSUE THREAD

**Issue by richtera** [wevm/frog-archived#498]
### Describe the bug

I am finding that inside of the code there is a browser.bot property which seems correct, but the code is checking browser.name. Although browser.name often works, if the user-agent is for example "Twitterbot/1.0" it will detect name=bot which is non-null and it will then redirect to browserLocation.
<img width="1096" alt="image" src="https://github.com/user-attachments/assets/a616c7e5-457f-46d0-a85a-228eff6d94b2">

### Link to Minimal Reproducible Example

I am going to patch, so I don't currently have an example

### Steps To Reproduce

I just compiled my frame using version and share the frame URL on twitter.
I can provide a URL after it's patched. I am going to change `browser?.name` to `!(browser as any)?.bot` (the typedefs for detect-browser don't make the bot flag public :( )

### Frog Version

0.17.4

### TypeScript Version

5.6.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

### Anything else?

Thanks for a cool library!

**Comment by richtera** [comment]
From the example in detect-browser it should probably say browser?.type === "browser"
```js
import { detect } from '../src';

const result = detect();
if (result) {
  switch (result.type) {
    case 'bot':
      // result is an instanceof BotInfo
      console.log(`found ${result.name} bot`);
      break;

    case 'bot-device':
      // result is an instanceof SearchBotDeviceInfo
      console.log(`found ${result.name} device bot`);
      break;

    case 'browser':
      // result is an instanceof BrowserInfo
      console.log(`found ${result.name} browser`);
      break;

    case 'node':
      // result is an instanceof NodeInfo
      console.log(`found node version ${result.version}`);
      break;
  }
}
```

**Comment by richtera** [comment]
Here is an example URL of my patched frog implementation [frame](https://upsharing.xyz/api/a/0x9a9d8711bf93cb060669798a2805686e272e0e79)

**Comment by dalechyn** [comment]
> Here is an example URL of my patched frog implementation [frame](https://upsharing.xyz/api/a/0x9a9d8711bf93cb060669798a2805686e272e0e79)

fyk can't see frame meta tags here

**Comment by dalechyn** [comment]
Can you please try out `frog@0.17.4-fix-browser-location.20241011T000723`?

**Comment by richtera** [comment]
> > Here is an example URL of my patched frog implementation [frame](https://upsharing.xyz/api/a/0x9a9d8711bf93cb060669798a2805686e272e0e79)
> 
> 
> 
> fyk can't see frame meta tags here

Yes that's the problem and your fix is identical to my patch. I think we're good this way. If you curl and send User-Agent: Twitterbot/1.0 for example you'd see the metadata and not redirect to browserLocation which doesn't have dynamic metadata.
