### ISSUE TITLE
Len's frame buttonValue undefined when buttonIndex is valid 

### ISSUE THREAD

**Issue by XhrCkYsSgZokJL** [wevm/frog-archived#524]
### Describe the bug

I am testing a frame on lens [https://hey.xyz/posts/0x01cb1c-0x07-DA-2e934123](url) 

After tapping "open", for every button I click, the buttonValue registers a value of "undefined". 

`const { buttonValue, inputText } = context;
// buttonValue is always undefined for a Lens frame
`

I'm expecting the buttonValue to be a valid string like 'unpaidBuyer-checkoutFlow' which corresponds to the "Checkout" button press. 

`export function getBuyerNormalCheckoutIntent(): FrameIntent {
  return <Button value='unpaidBuyer-checkoutFlow'>Checkout</Button>;
}` 

Logging the FrameContext's frameData shows the correct buttonIndex is recorded. 

`{
     "identityToken":"<redacted>",
     "unixTimestamp":1732169144,
     "actionResponse":"",
     "buttonIndex":4,
     "deadline":1732170942,
     "inputText":"",
     "profileId":"<redacted>",
     "pubId":"<redacted>",
     "specVersion":"1.0.0",
     "state":"",
     "url":"https://dev.hopscotch.trade/deal/frame/100"
}`

So there seems to be something about a Len's frame in which the buttonIndex does not translate into a valid buttonValue.  

### Steps To Reproduce

> async function handleNormalFrame(
>   context: FrameContext<ContextVariables>
> ): Promise<TypedResponse<FrameResponse>> {
>
>   console.log(JSON.stringify(context.frameData));
>   console.log(context.buttonIndex);
>   console.log(context.buttonValue);
> 
> return context.res({
>   action: ...,
>   image: ...,
>   intents: ...,
>   headers: ...,
> });

### Frog Version

0.18.2

### TypeScript Version

5.6.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by XhrCkYsSgZokJL** [comment]
Adding additional information. 
Appears "state" is an empty string and likely why buttonValue is undefined (previousButtonValues comes from here?).

The frame works fine in Farcaster with no explicit state management. 
Need to understand if I should be explicitly setting this state for Lens?

**Comment by dalechyn** [comment]
I'm sorry but the library is focused on Farcaster frames, without mentioning the support of Lens frames.

I'd suggest you taking a look at what you receive at `messageToFrameData` function located at `_lib/utils/verifyFrame.js`.

That said, I'll close the issue and maybe will respond here back and forth helping you to debug this, but this library isn't maintaining support of Lens frames.
