### ISSUE TITLE
Verification doesn't work on dev debugger

### ISSUE THREAD

**Issue by spennyp** [wevm/frog-archived#74]
### Describe the bug

Frame verification doesn't work in local dev debugger.

### Steps To Reproduce

1. `yarn create frog -t next`
2. Add the hub api: 
![image](https://github.com/wevm/frog/assets/31705429/d87f0076-e7bb-4e7c-969a-5eba596b5847)
3. Run the app, open dev server, and connect farcaster account
4. Interact with the frame
5. See error in console with verification: 
![image](https://github.com/wevm/frog/assets/31705429/491d9633-1d4d-4357-83f6-510c8438a3a4)

### Frog Version

0.2.14

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by ChangoMan** [comment]
Can you update to the latest version of frog at `0.3.3` and see if it works? I had a verification issue in prod and updating to the latest release fixed it.

Also I believe `hubApiUrl` is deprecated in the latest version, you can try 

```
import { pinata } from 'frog/hubs'

const app = new Frog({
  hub: pinata(),
})
```

**Comment by jxom** [comment]
Should work now!
