### ISSUE TITLE
Button.Transaction is not visible in Frame Preview

### ISSUE THREAD

**Issue by etherik** [wevm/frog-archived#88]
### Describe the bug

I am attempting to use a Button.Transaction in a frame. The expected behavior is that the transaction button will be rendered in Frog's Frame Preview. The observed behavior is that no button is visible in the Frame Preview, although fc:frame:button:<int> with its associated values does appear in the Dev Panel. The button _is_ visible when the same frame is viewed in the Farcaster Frame Validator.

### Link to Minimal Reproducible Example

https://gist.github.com/etherik/41450fff77957b1d5ecf0e71770a1111

### Steps To Reproduce

1.  Scaffold a new project with `yarn create frog`
2. Replace `index.tsx` with the the code from this [gist](https://gist.github.com/etherik/41450fff77957b1d5ecf0e71770a1111)
3. Run the frog dev server with `yarn dev`.
4. Navigate to the Frame Preview at the dev server URL, e.g. http://localhost:5173/api
5. Observe that the Button.Transaction button is not visible.

### Frog Version

0.3.0

### TypeScript Version

5.3.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by jxom** [comment]
Transaction support hasn't been implemented in the devtools yet. Should be in there tomorrow.

**Comment by tmm** [comment]
Buttons should show up now. Still working on full support (e.g. connect wallet, send transaction, etc.)
