### ISSUE TITLE
Ngrok proxy throwing error

### ISSUE THREAD

**Issue by gskril** [wevm/frog-archived#99]
### Describe the bug

I run `npx frog --proxy ngrok` expecting it to log the ngrok URL but instead it throws the following error:
```
Error: Ngrok Error: Error: failed to connect session: Usage of ngrok requires a verified account and authtoken.
```

When I run `npx frog dev`, then `ngrok http 5173` in another terminal window, I get the expected result. 

To verify a valid configuration of ngrok, I ran `ngrok config check` and get the response `Valid configuration file at /Users/Greg/.ngrok2/ngrok.yml`.

### Frog Version

0.4.4

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by tmm** [comment]
`frog dev --proxy ngrok` uses the official `ngrok` library and requires [`NGROK_AUTHTOKEN`](https://github.com/ngrok/ngrok-javascript?tab=readme-ov-file#quickstart) to be set (`ngrok.yml` is a configuration file [specifically for the ngrok agent](https://github.com/ngrok/ngrok-javascript/issues/110#issuecomment-1877797387)).

**Comment by gskril** [comment]
Ah that worked, thanks!
